[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Mini Pupper"
authors = [{name = "Afreez", email = "afreez@mangdang.net"}]
dynamic = ["version", "description"]
